openapi: 3.1.0
info:
  title: Household Service API
  version: 1.0.0
  x-domain: intake
  x-api-type: system
  x-status: stable
  x-visibility: internal
  description: |
    REST API for managing household records. The specification defines CRUD operations
    for creating, reading, updating, and deleting households.
  contact:
    name: API Support
    email: support@example.com
servers:
- url: https://api.example.com
  description: Production server
- url: http://localhost:8080
  description: Local development server
tags:
- name: Households
  description: Manage household records.
paths:
  "/households":
    get:
      summary: List households
      description: Retrieve a paginated list of households.
      operationId: listHouseholds
      tags:
      - Households
      parameters:
      - "$ref": "./components/parameters.yaml#/SearchQueryParam"
      - "$ref": "./components/parameters.yaml#/LimitParam"
      - "$ref": "./components/parameters.yaml#/OffsetParam"
      responses:
        '200':
          description: A paginated collection of households.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HouseholdList"
        '400':
          "$ref": "./components/responses.yaml#/BadRequest"
        '500':
          "$ref": "./components/responses.yaml#/InternalError"
    post:
      summary: Create a household
      description: Create a new household record.
      operationId: createHousehold
      tags:
      - Households
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/HouseholdCreate"
      responses:
        '201':
          description: Household created successfully.
          headers:
            Location:
              description: URL of the newly created household resource.
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Household"
        '400':
          "$ref": "./components/responses.yaml#/BadRequest"
        '422':
          "$ref": "./components/responses.yaml#/UnprocessableEntity"
        '500':
          "$ref": "./components/responses.yaml#/InternalError"
  "/households/{householdId}":
    parameters:
    - "$ref": "#/components/parameters/HouseholdIdParam"
    get:
      summary: Get a household
      description: Retrieve a single household by identifier.
      operationId: getHousehold
      tags:
      - Households
      responses:
        '200':
          description: Household retrieved successfully.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Household"
              examples:
                HouseholdExample1:
                  "$ref": "./households-examples.yaml#/HouseholdExample1"
        '404':
          "$ref": "./components/responses.yaml#/NotFound"
        '500':
          "$ref": "./components/responses.yaml#/InternalError"
    patch:
      summary: Update a household
      description: Apply partial updates to an existing household.
      operationId: updateHousehold
      tags:
      - Households
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/HouseholdUpdate"
      responses:
        '200':
          description: Household updated successfully.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Household"
        '400':
          "$ref": "./components/responses.yaml#/BadRequest"
        '404':
          "$ref": "./components/responses.yaml#/NotFound"
        '422':
          "$ref": "./components/responses.yaml#/UnprocessableEntity"
        '500':
          "$ref": "./components/responses.yaml#/InternalError"
    delete:
      summary: Delete a household
      description: Permanently remove a household record.
      operationId: deleteHousehold
      tags:
      - Households
      responses:
        '204':
          description: Household deleted successfully.
        '404':
          "$ref": "./components/responses.yaml#/NotFound"
        '500':
          "$ref": "./components/responses.yaml#/InternalError"
components:
  parameters:
    HouseholdIdParam:
      name: householdId
      in: path
      required: true
      description: Unique identifier of the household.
      schema:
        type: string
        format: uuid
      example: a1b2c3d4-e5f6-7890-abcd-ef1234567890
  schemas:
    Household:
      type: object
      description: Represents a household unit with multiple members.
      additionalProperties: false
      required:
      - id
      - members
      - homeAddress
      - createdAt
      - updatedAt
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the household.
          readOnly: true
        homeAddress:
          "$ref": "./components/contact.yaml#/Address"
          description: Home address of the household.
        mailingAddress:
          "$ref": "./components/contact.yaml#/Address"
          description: Mailing address if different from home address.
        phoneNumber:
          "$ref": "./components/contact.yaml#/PhoneNumber"
          description: Primary phone number for the household.
        members:
          type: array
          description: List of household members with their relationship to the head of household.
          minItems: 1
          items:
            type: object
            additionalProperties: false
            required:
            - personId
            - relationship
            properties:
              personId:
                type: string
                format: uuid
                description: Reference to the person's unique identifier.
              relationship:
                type: string
                description: Relationship to the head of household.
                enum:
                - head_of_household
                - spouse
                - husband
                - wife
                - partner
                - child
                - parent
                - sibling
                - grandparent
                - grandchild
                - other_relative
                - non_relative
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the household record was created.
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the household record was last updated.
          readOnly: true
    HouseholdCreate:
      allOf:
      - "$ref": "#/components/schemas/Household"
      - type: object
        description: |
          Payload to create a new household record.

          Note: id, createdAt, and updatedAt are server-generated (readOnly) and will be returned in the response.
    HouseholdUpdate:
      allOf:
      - "$ref": "#/components/schemas/Household"
      - type: object
        description: |
          Payload to update household members. Partial updates are supported.

          Note: id, createdAt, and updatedAt are server-generated (readOnly) and cannot be updated.
        minProperties: 1
    HouseholdList:
      type: object
      additionalProperties: false
      required:
      - items
      - total
      - limit
      - offset
      properties:
        items:
          type: array
          items:
            "$ref": "#/components/schemas/Household"
        total:
          type: integer
          minimum: 0
          description: Total number of households available.
        limit:
          type: integer
          minimum: 1
          maximum: 100
          description: Maximum number of households requested.
        offset:
          type: integer
          minimum: 0
          description: Number of items skipped before the current page.
        hasNext:
          type: boolean
          description: Indicates whether more households are available beyond the current
            page.
