// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type Widget = {
    id?: string;
    name?: string;
};

export type WidgetList = {
    items?: Array<{
        id?: string;
        name?: string;
    }>;
    total?: number;
};
