// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zWidget = z.object({
    id: z.optional(z.string()),
    name: z.optional(z.string())
});

export const zWidgetList = z.object({
    items: z.optional(z.array(z.object({
        id: z.optional(z.string()),
        name: z.optional(z.string())
    }))),
    total: z.optional(z.int())
});
