// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AcknowledgeNoticeData, AcknowledgeNoticeErrors, AcknowledgeNoticeResponses, CreateNoticeData, CreateNoticeErrors, CreateNoticeResponses, DeleteNoticeData, DeleteNoticeErrors, DeleteNoticeResponses, EvaluateUrgencyData, EvaluateUrgencyErrors, EvaluateUrgencyResponses, ExpireNoticeData, ExpireNoticeErrors, ExpireNoticeResponses, GetNoticeData, GetNoticeErrors, GetNoticeResponses, ListNoticesData, ListNoticesErrors, ListNoticesResponses, SendNoticeData, SendNoticeErrors, SendNoticeResponses, UpdateNoticeData, UpdateNoticeErrors, UpdateNoticeResponses } from './types.gen';
import { zAcknowledgeNoticeData, zAcknowledgeNoticeResponse, zCreateNoticeData, zCreateNoticeResponse, zDeleteNoticeData, zDeleteNoticeResponse, zEvaluateUrgencyData, zEvaluateUrgencyResponse, zExpireNoticeData, zExpireNoticeResponse, zGetNoticeData, zGetNoticeResponse, zListNoticesData, zListNoticesResponse, zSendNoticeData, zSendNoticeResponse, zUpdateNoticeData, zUpdateNoticeResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List notices
 */
export const listNotices = <ThrowOnError extends boolean = false>(options?: Options<ListNoticesData, ThrowOnError>) => (options?.client ?? client).get<ListNoticesResponses, ListNoticesErrors, ThrowOnError>({
    requestValidator: async (data) => await zListNoticesData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zListNoticesResponse.parseAsync(data),
    url: '/alerts/notices',
    ...options
});

/**
 * Create a notice
 */
export const createNotice = <ThrowOnError extends boolean = false>(options: Options<CreateNoticeData, ThrowOnError>) => (options.client ?? client).post<CreateNoticeResponses, CreateNoticeErrors, ThrowOnError>({
    requestValidator: async (data) => await zCreateNoticeData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zCreateNoticeResponse.parseAsync(data),
    url: '/alerts/notices',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a notice
 */
export const deleteNotice = <ThrowOnError extends boolean = false>(options: Options<DeleteNoticeData, ThrowOnError>) => (options.client ?? client).delete<DeleteNoticeResponses, DeleteNoticeErrors, ThrowOnError>({
    requestValidator: async (data) => await zDeleteNoticeData.parseAsync(data),
    responseValidator: async (data) => await zDeleteNoticeResponse.parseAsync(data),
    url: '/alerts/notices/{noticeId}',
    ...options
});

/**
 * Get a notice
 */
export const getNotice = <ThrowOnError extends boolean = false>(options: Options<GetNoticeData, ThrowOnError>) => (options.client ?? client).get<GetNoticeResponses, GetNoticeErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetNoticeData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zGetNoticeResponse.parseAsync(data),
    url: '/alerts/notices/{noticeId}',
    ...options
});

/**
 * Update a notice
 */
export const updateNotice = <ThrowOnError extends boolean = false>(options: Options<UpdateNoticeData, ThrowOnError>) => (options.client ?? client).patch<UpdateNoticeResponses, UpdateNoticeErrors, ThrowOnError>({
    requestValidator: async (data) => await zUpdateNoticeData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zUpdateNoticeResponse.parseAsync(data),
    url: '/alerts/notices/{noticeId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Send notice
 *
 * Trigger the send transition (draft → sent).
 */
export const sendNotice = <ThrowOnError extends boolean = false>(options: Options<SendNoticeData, ThrowOnError>) => (options.client ?? client).post<SendNoticeResponses, SendNoticeErrors, ThrowOnError>({
    requestValidator: async (data) => await zSendNoticeData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zSendNoticeResponse.parseAsync(data),
    url: '/alerts/notices/{noticeId}/send',
    ...options
});

/**
 * Acknowledge notice
 *
 * Trigger the acknowledge transition (sent → acknowledged).
 */
export const acknowledgeNotice = <ThrowOnError extends boolean = false>(options: Options<AcknowledgeNoticeData, ThrowOnError>) => (options.client ?? client).post<AcknowledgeNoticeResponses, AcknowledgeNoticeErrors, ThrowOnError>({
    requestValidator: async (data) => await zAcknowledgeNoticeData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zAcknowledgeNoticeResponse.parseAsync(data),
    url: '/alerts/notices/{noticeId}/acknowledge',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Expire notice
 *
 * Trigger the expire transition (sent | acknowledged → expired).
 */
export const expireNotice = <ThrowOnError extends boolean = false>(options: Options<ExpireNoticeData, ThrowOnError>) => (options.client ?? client).post<ExpireNoticeResponses, ExpireNoticeErrors, ThrowOnError>({
    requestValidator: async (data) => await zExpireNoticeData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zExpireNoticeResponse.parseAsync(data),
    url: '/alerts/notices/{noticeId}/expire',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Evaluate urgency
 */
export const evaluateUrgency = <ThrowOnError extends boolean = false>(options: Options<EvaluateUrgencyData, ThrowOnError>) => (options.client ?? client).post<EvaluateUrgencyResponses, EvaluateUrgencyErrors, ThrowOnError>({
    requestValidator: async (data) => await zEvaluateUrgencyData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zEvaluateUrgencyResponse.parseAsync(data),
    url: '/alerts/notices/evaluate-urgency',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
