// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type Notice = {
    readonly id: string;
    status: 'draft' | 'sent' | 'acknowledged' | 'expired';
    /**
     * Category of notice
     */
    category?: 'system' | 'caseworker' | 'administrative';
    message?: string;
    readonly createdAt: string;
    readonly updatedAt: string;
    /**
     * County-specific code for routing this notice
     */
    county_code?: string;
};

export type NoticeCreate = {
    message: string;
    /**
     * Category of notice
     */
    category?: 'system' | 'caseworker' | 'administrative';
    caseWorkerId?: string;
};

export type NoticeUpdate = {
    message?: string;
    /**
     * Category of notice
     */
    category?: 'system' | 'caseworker' | 'administrative';
};

export type NoticeList = {
    items?: Array<{
        readonly id: string;
        status: 'draft' | 'sent' | 'acknowledged' | 'expired';
        /**
         * Category of notice
         */
        category?: 'system' | 'caseworker' | 'administrative';
        message?: string;
        readonly createdAt: string;
        readonly updatedAt: string;
        /**
         * County-specific code for routing this notice
         */
        county_code?: string;
    }>;
    total?: number;
    limit?: number;
    offset?: number;
    hasNext?: boolean;
};

export type ExpireRequest = {
    /**
     * Why the notice is being expired
     */
    reason: 'superseded' | 'deadline_passed' | 'cancelled';
    /**
     * Optional additional context
     */
    notes?: string;
};

/**
 * Input data for urgency evaluation. All fields are optional — partial inputs trigger partial evaluation.
 */
export type UrgencyRequest = {
    notice?: {
        status?: string;
        daysSinceCreated?: number;
    };
    policy?: {
        urgencyThresholdDays?: number;
    };
};

/**
 * Map of output fact names to their evaluation result. Only output facts are included; intermediate facts are not returned.
 *
 */
export type UrgencyResponse = {
    [key: string]: {
        state: 'complete';
        /**
         * The computed value.
         */
        value: unknown;
    } | {
        state: 'placeholder';
        /**
         * The computed value, derived using one or more schema defaults.
         */
        value: unknown;
    } | {
        state: 'missing';
        value: null;
        /**
         * Input paths required to resolve this fact.
         */
        missing: Array<string>;
    } | {
        state: 'error';
        value: null;
        /**
         * The reason evaluation failed.
         */
        message: string;
    };
};

export type NoticeWritable = {
    status: 'draft' | 'sent' | 'acknowledged' | 'expired';
    /**
     * Category of notice
     */
    category?: 'system' | 'caseworker' | 'administrative';
    message?: string;
    /**
     * County-specific code for routing this notice
     */
    county_code?: string;
};

export type NoticeListWritable = {
    items?: Array<{
        status: 'draft' | 'sent' | 'acknowledged' | 'expired';
        /**
         * Category of notice
         */
        category?: 'system' | 'caseworker' | 'administrative';
        message?: string;
        /**
         * County-specific code for routing this notice
         */
        county_code?: string;
    }>;
    total?: number;
    limit?: number;
    offset?: number;
    hasNext?: boolean;
};

export type NoticeIdParam = string;

export type ListNoticesData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        status?: string;
        limit?: number;
        offset?: number;
    };
    url: '/alerts/notices';
};

export type ListNoticesErrors = {
    /**
     * Bad request — validation failed
     */
    400: {
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        message?: string;
    };
};

export type ListNoticesError = ListNoticesErrors[keyof ListNoticesErrors];

export type ListNoticesResponses = {
    /**
     * OK
     */
    200: {
        items?: Array<{
            readonly id: string;
            status: 'draft' | 'sent' | 'acknowledged' | 'expired';
            /**
             * Category of notice
             */
            category?: 'system' | 'caseworker' | 'administrative';
            message?: string;
            readonly createdAt: string;
            readonly updatedAt: string;
            /**
             * County-specific code for routing this notice
             */
            county_code?: string;
            /**
             * Expanded CaseWorker.
             */
            reviewer?: {
                [key: string]: unknown;
            };
            /**
             * Expanded CaseWorker.
             */
            caseWorker?: {
                [key: string]: unknown;
            };
        }>;
        total?: number;
        limit?: number;
        offset?: number;
        hasNext?: boolean;
    };
};

export type ListNoticesResponse = ListNoticesResponses[keyof ListNoticesResponses];

export type CreateNoticeData = {
    body: {
        message: string;
        /**
         * Category of notice
         */
        category?: 'system' | 'caseworker' | 'administrative';
        caseWorkerId?: string;
    };
    path?: never;
    query?: never;
    url: '/alerts/notices';
};

export type CreateNoticeErrors = {
    /**
     * Bad request — validation failed
     */
    400: {
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        message?: string;
    };
};

export type CreateNoticeError = CreateNoticeErrors[keyof CreateNoticeErrors];

export type CreateNoticeResponses = {
    /**
     * Created
     */
    201: {
        readonly id: string;
        status: 'draft' | 'sent' | 'acknowledged' | 'expired';
        /**
         * Category of notice
         */
        category?: 'system' | 'caseworker' | 'administrative';
        message?: string;
        readonly createdAt: string;
        readonly updatedAt: string;
        /**
         * County-specific code for routing this notice
         */
        county_code?: string;
        /**
         * Expanded CaseWorker.
         */
        reviewer?: {
            [key: string]: unknown;
        };
        /**
         * Expanded CaseWorker.
         */
        caseWorker?: {
            [key: string]: unknown;
        };
    };
};

export type CreateNoticeResponse = CreateNoticeResponses[keyof CreateNoticeResponses];

export type DeleteNoticeData = {
    body?: never;
    path: {
        noticeId: string;
    };
    query?: never;
    url: '/alerts/notices/{noticeId}';
};

export type DeleteNoticeErrors = {
    /**
     * Resource not found
     */
    404: {
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        message?: string;
    };
};

export type DeleteNoticeError = DeleteNoticeErrors[keyof DeleteNoticeErrors];

export type DeleteNoticeResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteNoticeResponse = DeleteNoticeResponses[keyof DeleteNoticeResponses];

export type GetNoticeData = {
    body?: never;
    path: {
        noticeId: string;
    };
    query?: never;
    url: '/alerts/notices/{noticeId}';
};

export type GetNoticeErrors = {
    /**
     * Resource not found
     */
    404: {
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        message?: string;
    };
};

export type GetNoticeError = GetNoticeErrors[keyof GetNoticeErrors];

export type GetNoticeResponses = {
    /**
     * OK
     */
    200: {
        readonly id: string;
        status: 'draft' | 'sent' | 'acknowledged' | 'expired';
        /**
         * Category of notice
         */
        category?: 'system' | 'caseworker' | 'administrative';
        message?: string;
        readonly createdAt: string;
        readonly updatedAt: string;
        /**
         * County-specific code for routing this notice
         */
        county_code?: string;
        /**
         * Expanded CaseWorker.
         */
        reviewer?: {
            [key: string]: unknown;
        };
        /**
         * Expanded CaseWorker.
         */
        caseWorker?: {
            [key: string]: unknown;
        };
    };
};

export type GetNoticeResponse = GetNoticeResponses[keyof GetNoticeResponses];

export type UpdateNoticeData = {
    body: {
        message?: string;
        /**
         * Category of notice
         */
        category?: 'system' | 'caseworker' | 'administrative';
    };
    path: {
        noticeId: string;
    };
    query?: never;
    url: '/alerts/notices/{noticeId}';
};

export type UpdateNoticeErrors = {
    /**
     * Bad request — validation failed
     */
    400: {
        message?: string;
    };
    /**
     * Resource not found
     */
    404: {
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        message?: string;
    };
};

export type UpdateNoticeError = UpdateNoticeErrors[keyof UpdateNoticeErrors];

export type UpdateNoticeResponses = {
    /**
     * OK
     */
    200: {
        readonly id: string;
        status: 'draft' | 'sent' | 'acknowledged' | 'expired';
        /**
         * Category of notice
         */
        category?: 'system' | 'caseworker' | 'administrative';
        message?: string;
        readonly createdAt: string;
        readonly updatedAt: string;
        /**
         * County-specific code for routing this notice
         */
        county_code?: string;
        /**
         * Expanded CaseWorker.
         */
        reviewer?: {
            [key: string]: unknown;
        };
        /**
         * Expanded CaseWorker.
         */
        caseWorker?: {
            [key: string]: unknown;
        };
    };
};

export type UpdateNoticeResponse = UpdateNoticeResponses[keyof UpdateNoticeResponses];

export type SendNoticeData = {
    body?: never;
    path: {
        noticeId: string;
    };
    query?: never;
    url: '/alerts/notices/{noticeId}/send';
};

export type SendNoticeErrors = {
    /**
     * Bad request — validation failed
     */
    400: {
        message?: string;
    };
    /**
     * Resource not found
     */
    404: {
        message?: string;
    };
    /**
     * Conflict — state transition not allowed
     */
    409: {
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        message?: string;
    };
};

export type SendNoticeError = SendNoticeErrors[keyof SendNoticeErrors];

export type SendNoticeResponses = {
    /**
     * Transition applied successfully.
     */
    200: {
        readonly id: string;
        status: 'draft' | 'sent' | 'acknowledged' | 'expired';
        /**
         * Category of notice
         */
        category?: 'system' | 'caseworker' | 'administrative';
        message?: string;
        readonly createdAt: string;
        readonly updatedAt: string;
        /**
         * County-specific code for routing this notice
         */
        county_code?: string;
        /**
         * Expanded CaseWorker.
         */
        reviewer?: {
            [key: string]: unknown;
        };
        /**
         * Expanded CaseWorker.
         */
        caseWorker?: {
            [key: string]: unknown;
        };
    };
};

export type SendNoticeResponse = SendNoticeResponses[keyof SendNoticeResponses];

export type AcknowledgeNoticeData = {
    body: {
        /**
         * ID of the person acknowledging the notice
         */
        acknowledgedBy: string;
    };
    path: {
        noticeId: string;
    };
    query?: never;
    url: '/alerts/notices/{noticeId}/acknowledge';
};

export type AcknowledgeNoticeErrors = {
    /**
     * Bad request — validation failed
     */
    400: {
        message?: string;
    };
    /**
     * Resource not found
     */
    404: {
        message?: string;
    };
    /**
     * Conflict — state transition not allowed
     */
    409: {
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        message?: string;
    };
};

export type AcknowledgeNoticeError = AcknowledgeNoticeErrors[keyof AcknowledgeNoticeErrors];

export type AcknowledgeNoticeResponses = {
    /**
     * Transition applied successfully.
     */
    200: {
        readonly id: string;
        status: 'draft' | 'sent' | 'acknowledged' | 'expired';
        /**
         * Category of notice
         */
        category?: 'system' | 'caseworker' | 'administrative';
        message?: string;
        readonly createdAt: string;
        readonly updatedAt: string;
        /**
         * County-specific code for routing this notice
         */
        county_code?: string;
        /**
         * Expanded CaseWorker.
         */
        reviewer?: {
            [key: string]: unknown;
        };
        /**
         * Expanded CaseWorker.
         */
        caseWorker?: {
            [key: string]: unknown;
        };
    };
};

export type AcknowledgeNoticeResponse = AcknowledgeNoticeResponses[keyof AcknowledgeNoticeResponses];

export type ExpireNoticeData = {
    body: {
        /**
         * Why the notice is being expired
         */
        reason: 'superseded' | 'deadline_passed' | 'cancelled';
        /**
         * Optional additional context
         */
        notes?: string;
    };
    path: {
        noticeId: string;
    };
    query?: never;
    url: '/alerts/notices/{noticeId}/expire';
};

export type ExpireNoticeErrors = {
    /**
     * Bad request — validation failed
     */
    400: {
        message?: string;
    };
    /**
     * Resource not found
     */
    404: {
        message?: string;
    };
    /**
     * Conflict — state transition not allowed
     */
    409: {
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        message?: string;
    };
};

export type ExpireNoticeError = ExpireNoticeErrors[keyof ExpireNoticeErrors];

export type ExpireNoticeResponses = {
    /**
     * Transition applied successfully.
     */
    200: {
        readonly id: string;
        status: 'draft' | 'sent' | 'acknowledged' | 'expired';
        /**
         * Category of notice
         */
        category?: 'system' | 'caseworker' | 'administrative';
        message?: string;
        readonly createdAt: string;
        readonly updatedAt: string;
        /**
         * County-specific code for routing this notice
         */
        county_code?: string;
        /**
         * Expanded CaseWorker.
         */
        reviewer?: {
            [key: string]: unknown;
        };
        /**
         * Expanded CaseWorker.
         */
        caseWorker?: {
            [key: string]: unknown;
        };
    };
};

export type ExpireNoticeResponse = ExpireNoticeResponses[keyof ExpireNoticeResponses];

export type EvaluateUrgencyData = {
    /**
     * Input data for urgency evaluation. All fields are optional — partial inputs trigger partial evaluation.
     */
    body: {
        notice?: {
            status?: string;
            daysSinceCreated?: number;
        };
        policy?: {
            urgencyThresholdDays?: number;
        };
    };
    path?: never;
    query?: never;
    url: '/alerts/notices/evaluate-urgency';
};

export type EvaluateUrgencyErrors = {
    /**
     * Bad request — validation failed
     */
    400: {
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        message?: string;
    };
};

export type EvaluateUrgencyError = EvaluateUrgencyErrors[keyof EvaluateUrgencyErrors];

export type EvaluateUrgencyResponses = {
    /**
     * Map of output fact names to their evaluation result. Only output facts are included; intermediate facts are not returned.
     *
     */
    200: {
        [key: string]: {
            state: 'complete';
            /**
             * The computed value.
             */
            value: unknown;
        } | {
            state: 'placeholder';
            /**
             * The computed value, derived using one or more schema defaults.
             */
            value: unknown;
        } | {
            state: 'missing';
            value: null;
            /**
             * Input paths required to resolve this fact.
             */
            missing: Array<string>;
        } | {
            state: 'error';
            value: null;
            /**
             * The reason evaluation failed.
             */
            message: string;
        };
    };
};

export type EvaluateUrgencyResponse = EvaluateUrgencyResponses[keyof EvaluateUrgencyResponses];

export const NoticeCategory = {
  SYSTEM: 'system',
  CASEWORKER: 'caseworker',
  ADMINISTRATIVE: 'administrative',
} as const;
export type NoticeCategory = (typeof NoticeCategory)[keyof typeof NoticeCategory];
