// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zNotice = z.object({
    id: z.uuid().readonly(),
    status: z.enum([
        'draft',
        'sent',
        'acknowledged',
        'expired'
    ]),
    category: z.optional(z.enum([
        'system',
        'caseworker',
        'administrative'
    ])),
    message: z.optional(z.string()),
    createdAt: z.iso.datetime({ offset: true }).readonly(),
    updatedAt: z.iso.datetime({ offset: true }).readonly(),
    county_code: z.optional(z.string())
});

export const zNoticeCreate = z.object({
    message: z.string(),
    category: z.optional(z.enum([
        'system',
        'caseworker',
        'administrative'
    ])),
    caseWorkerId: z.optional(z.uuid())
});

export const zNoticeUpdate = z.object({
    message: z.optional(z.string()),
    category: z.optional(z.enum([
        'system',
        'caseworker',
        'administrative'
    ]))
});

export const zNoticeList = z.object({
    items: z.optional(z.array(z.object({
        id: z.uuid().readonly(),
        status: z.enum([
            'draft',
            'sent',
            'acknowledged',
            'expired'
        ]),
        category: z.optional(z.enum([
            'system',
            'caseworker',
            'administrative'
        ])),
        message: z.optional(z.string()),
        createdAt: z.iso.datetime({ offset: true }).readonly(),
        updatedAt: z.iso.datetime({ offset: true }).readonly(),
        county_code: z.optional(z.string())
    }))),
    total: z.optional(z.int()),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    hasNext: z.optional(z.boolean())
});

export const zExpireRequest = z.object({
    reason: z.enum([
        'superseded',
        'deadline_passed',
        'cancelled'
    ]),
    notes: z.optional(z.string())
});

/**
 * Input data for urgency evaluation. All fields are optional — partial inputs trigger partial evaluation.
 */
export const zUrgencyRequest = z.object({
    notice: z.optional(z.object({
        status: z.optional(z.string()),
        daysSinceCreated: z.optional(z.int())
    })),
    policy: z.optional(z.object({
        urgencyThresholdDays: z.optional(z.int()).default(3)
    }))
});

/**
 * Map of output fact names to their evaluation result. Only output facts are included; intermediate facts are not returned.
 *
 */
export const zUrgencyResponse = z.record(z.string(), z.union([
    z.object({
        state: z.enum(['complete']),
        value: z.unknown()
    }),
    z.object({
        state: z.enum(['placeholder']),
        value: z.unknown()
    }),
    z.object({
        state: z.enum(['missing']),
        value: z.null(),
        missing: z.array(z.string())
    }),
    z.object({
        state: z.enum(['error']),
        value: z.null(),
        message: z.string()
    })
]));

export const zNoticeWritable = z.object({
    status: z.enum([
        'draft',
        'sent',
        'acknowledged',
        'expired'
    ]),
    category: z.optional(z.enum([
        'system',
        'caseworker',
        'administrative'
    ])),
    message: z.optional(z.string()),
    county_code: z.optional(z.string())
});

export const zNoticeListWritable = z.object({
    items: z.optional(z.array(z.object({
        status: z.enum([
            'draft',
            'sent',
            'acknowledged',
            'expired'
        ]),
        category: z.optional(z.enum([
            'system',
            'caseworker',
            'administrative'
        ])),
        message: z.optional(z.string()),
        county_code: z.optional(z.string())
    }))),
    total: z.optional(z.int()),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    hasNext: z.optional(z.boolean())
});

export const zNoticeIdParam = z.uuid();

export const zListNoticesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        q: z.optional(z.string()),
        status: z.optional(z.string()),
        limit: z.optional(z.int()),
        offset: z.optional(z.int())
    }))
});

/**
 * OK
 */
export const zListNoticesResponse = z.object({
    items: z.optional(z.array(z.object({
        id: z.uuid().readonly(),
        status: z.enum([
            'draft',
            'sent',
            'acknowledged',
            'expired'
        ]),
        category: z.optional(z.enum([
            'system',
            'caseworker',
            'administrative'
        ])),
        message: z.optional(z.string()),
        createdAt: z.iso.datetime({ offset: true }).readonly(),
        updatedAt: z.iso.datetime({ offset: true }).readonly(),
        county_code: z.optional(z.string()),
        reviewer: z.optional(z.record(z.string(), z.unknown())),
        caseWorker: z.optional(z.record(z.string(), z.unknown()))
    }))),
    total: z.optional(z.int()),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    hasNext: z.optional(z.boolean())
});

export const zCreateNoticeData = z.object({
    body: z.object({
        message: z.string(),
        category: z.optional(z.enum([
            'system',
            'caseworker',
            'administrative'
        ])),
        caseWorkerId: z.optional(z.uuid())
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zCreateNoticeResponse = z.object({
    id: z.uuid().readonly(),
    status: z.enum([
        'draft',
        'sent',
        'acknowledged',
        'expired'
    ]),
    category: z.optional(z.enum([
        'system',
        'caseworker',
        'administrative'
    ])),
    message: z.optional(z.string()),
    createdAt: z.iso.datetime({ offset: true }).readonly(),
    updatedAt: z.iso.datetime({ offset: true }).readonly(),
    county_code: z.optional(z.string()),
    reviewer: z.optional(z.record(z.string(), z.unknown())),
    caseWorker: z.optional(z.record(z.string(), z.unknown()))
});

export const zDeleteNoticeData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        noticeId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * No Content
 */
export const zDeleteNoticeResponse = z.void();

export const zGetNoticeData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        noticeId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetNoticeResponse = z.object({
    id: z.uuid().readonly(),
    status: z.enum([
        'draft',
        'sent',
        'acknowledged',
        'expired'
    ]),
    category: z.optional(z.enum([
        'system',
        'caseworker',
        'administrative'
    ])),
    message: z.optional(z.string()),
    createdAt: z.iso.datetime({ offset: true }).readonly(),
    updatedAt: z.iso.datetime({ offset: true }).readonly(),
    county_code: z.optional(z.string()),
    reviewer: z.optional(z.record(z.string(), z.unknown())),
    caseWorker: z.optional(z.record(z.string(), z.unknown()))
});

export const zUpdateNoticeData = z.object({
    body: z.object({
        message: z.optional(z.string()),
        category: z.optional(z.enum([
            'system',
            'caseworker',
            'administrative'
        ]))
    }),
    path: z.object({
        noticeId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zUpdateNoticeResponse = z.object({
    id: z.uuid().readonly(),
    status: z.enum([
        'draft',
        'sent',
        'acknowledged',
        'expired'
    ]),
    category: z.optional(z.enum([
        'system',
        'caseworker',
        'administrative'
    ])),
    message: z.optional(z.string()),
    createdAt: z.iso.datetime({ offset: true }).readonly(),
    updatedAt: z.iso.datetime({ offset: true }).readonly(),
    county_code: z.optional(z.string()),
    reviewer: z.optional(z.record(z.string(), z.unknown())),
    caseWorker: z.optional(z.record(z.string(), z.unknown()))
});

export const zSendNoticeData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        noticeId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Transition applied successfully.
 */
export const zSendNoticeResponse = z.object({
    id: z.uuid().readonly(),
    status: z.enum([
        'draft',
        'sent',
        'acknowledged',
        'expired'
    ]),
    category: z.optional(z.enum([
        'system',
        'caseworker',
        'administrative'
    ])),
    message: z.optional(z.string()),
    createdAt: z.iso.datetime({ offset: true }).readonly(),
    updatedAt: z.iso.datetime({ offset: true }).readonly(),
    county_code: z.optional(z.string()),
    reviewer: z.optional(z.record(z.string(), z.unknown())),
    caseWorker: z.optional(z.record(z.string(), z.unknown()))
});

export const zAcknowledgeNoticeData = z.object({
    body: z.object({
        acknowledgedBy: z.string()
    }),
    path: z.object({
        noticeId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Transition applied successfully.
 */
export const zAcknowledgeNoticeResponse = z.object({
    id: z.uuid().readonly(),
    status: z.enum([
        'draft',
        'sent',
        'acknowledged',
        'expired'
    ]),
    category: z.optional(z.enum([
        'system',
        'caseworker',
        'administrative'
    ])),
    message: z.optional(z.string()),
    createdAt: z.iso.datetime({ offset: true }).readonly(),
    updatedAt: z.iso.datetime({ offset: true }).readonly(),
    county_code: z.optional(z.string()),
    reviewer: z.optional(z.record(z.string(), z.unknown())),
    caseWorker: z.optional(z.record(z.string(), z.unknown()))
});

export const zExpireNoticeData = z.object({
    body: z.object({
        reason: z.enum([
            'superseded',
            'deadline_passed',
            'cancelled'
        ]),
        notes: z.optional(z.string())
    }),
    path: z.object({
        noticeId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Transition applied successfully.
 */
export const zExpireNoticeResponse = z.object({
    id: z.uuid().readonly(),
    status: z.enum([
        'draft',
        'sent',
        'acknowledged',
        'expired'
    ]),
    category: z.optional(z.enum([
        'system',
        'caseworker',
        'administrative'
    ])),
    message: z.optional(z.string()),
    createdAt: z.iso.datetime({ offset: true }).readonly(),
    updatedAt: z.iso.datetime({ offset: true }).readonly(),
    county_code: z.optional(z.string()),
    reviewer: z.optional(z.record(z.string(), z.unknown())),
    caseWorker: z.optional(z.record(z.string(), z.unknown()))
});

export const zEvaluateUrgencyData = z.object({
    body: z.object({
        notice: z.optional(z.object({
            status: z.optional(z.string()),
            daysSinceCreated: z.optional(z.int())
        })),
        policy: z.optional(z.object({
            urgencyThresholdDays: z.optional(z.int()).default(3)
        }))
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Map of output fact names to their evaluation result. Only output facts are included; intermediate facts are not returned.
 *
 */
export const zEvaluateUrgencyResponse = z.record(z.string(), z.union([
    z.object({
        state: z.enum(['complete']),
        value: z.unknown()
    }),
    z.object({
        state: z.enum(['placeholder']),
        value: z.unknown()
    }),
    z.object({
        state: z.enum(['missing']),
        value: z.null(),
        missing: z.array(z.string())
    }),
    z.object({
        state: z.enum(['error']),
        value: z.null(),
        message: z.string()
    })
]));
