openapi: 3.1.0
info:
  title: Income Service API
  version: 1.0.0
  description: |
    REST API for managing income records. The specification defines CRUD operations
    for creating, reading, updating, and deleting income items.
  contact:
    name: API Support
    email: support@example.com
servers:
- url: https://api.example.com
  description: Production server
- url: http://localhost:8080
  description: Local development server
tags:
- name: Income
  description: Manage income records.
paths:
  "/income-items":
    get:
      summary: List income items
      description: Retrieve a paginated list of income items.
      operationId: listIncomeItems
      tags:
      - Income
      parameters:
      - "$ref": "./components/common-parameters.yaml#/LimitParam"
      - "$ref": "./components/common-parameters.yaml#/OffsetParam"
      responses:
        '200':
          description: A paginated collection of income items.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/IncomeItemList"
        '400':
          "$ref": "./components/common-responses.yaml#/BadRequest"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
    post:
      summary: Create an income item
      description: Create a new income item record.
      operationId: createIncomeItem
      tags:
      - Income
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/IncomeItemCreate"
      responses:
        '201':
          description: Income item created successfully.
          headers:
            Location:
              description: URL of the newly created income item resource.
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/IncomeItem"
        '400':
          "$ref": "./components/common-responses.yaml#/BadRequest"
        '409':
          "$ref": "./components/common-responses.yaml#/Conflict"
        '422':
          "$ref": "./components/common-responses.yaml#/UnprocessableEntity"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
  "/income-items/{incomeItemId}":
    parameters:
    - name: incomeItemId
      in: path
      required: true
      description: Unique identifier of the income item.
      schema:
        type: string
        format: uuid
    get:
      summary: Get an income item
      description: Retrieve a single income item by identifier.
      operationId: getIncomeItem
      tags:
      - Income
      responses:
        '200':
          description: Income item retrieved successfully.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/IncomeItem"
        '404':
          "$ref": "./components/common-responses.yaml#/NotFound"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
    patch:
      summary: Update an income item
      description: |
        Apply partial updates to an existing income item. The `type` field cannot
        be changed after creation.
      operationId: updateIncomeItem
      tags:
      - Income
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/IncomeItemUpdate"
      responses:
        '200':
          description: Income item updated successfully.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/IncomeItem"
        '400':
          "$ref": "./components/common-responses.yaml#/BadRequest"
        '404':
          "$ref": "./components/common-responses.yaml#/NotFound"
        '409':
          "$ref": "./components/common-responses.yaml#/Conflict"
        '422':
          "$ref": "./components/common-responses.yaml#/UnprocessableEntity"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
    delete:
      summary: Delete an income item
      description: Permanently remove an income item record.
      operationId: deleteIncomeItem
      tags:
      - Income
      responses:
        '204':
          description: Income item deleted successfully.
        '404':
          "$ref": "./components/common-responses.yaml#/NotFound"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
components:
  schemas:
    IncomeItem:
      "$ref": "./components/income.yaml#/Income"
    IncomeItemCreate:
      allOf:
      - "$ref": "./components/income.yaml#/Income"
      - type: object
        description: |
          Payload to create a new income item record.

          Note: id is server-generated (readOnly) and will be returned in the response.
    IncomeItemUpdate:
      allOf:
      - "$ref": "./components/income.yaml#/Income"
      - type: object
        description: |
          Payload to update one or more mutable fields of an existing income item.
          Partial updates are supported.

          Note: id is server-generated (readOnly) and cannot be updated.
          The `type` field cannot be changed after creation.
        minProperties: 1
    IncomeItemList:
      type: object
      additionalProperties: false
      required:
      - items
      - total
      - limit
      - offset
      properties:
        items:
          type: array
          items:
            "$ref": "#/components/schemas/IncomeItem"
        total:
          type: integer
          minimum: 0
          description: Total number of income items available.
        limit:
          type: integer
          minimum: 1
          maximum: 100
          description: Maximum number of income items requested.
        offset:
          type: integer
          minimum: 0
          description: Number of items skipped before the current page.

