#!/usr/bin/env node
/**
 * Builds dist/browser.js — a self-contained IIFE bundle of toGraph
 * for use in browser environments.
 *
 * Only the CEL evaluator and toGraph are included. The rules-doc compilation
 * path inside toGraph is dead code in the browser (browsers always receive
 * pre-compiled *-graph.yaml documents), but is harmless since compileRuleset
 * is never called when a compiled graph is passed.
 *
 * Exposed as: window.RulesEngine = { toGraph }
 *
 * Usage: node scripts/build-browser.js
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const srcDir  = resolve(__dirname, '..', 'src');
const distDir = resolve(__dirname, '..', 'dist');

mkdirSync(distDir, { recursive: true });

// ── cel.js ────────────────────────────────────────────────────────────────────
// No imports. Strip the `export` keyword only.

const celSrc = readFileSync(resolve(srcDir, 'cel.js'), 'utf8')
  .replace(/^export /m, '');

// ── evaluator.js ──────────────────────────────────────────────────────────────
// Strip import statements (compileRuleset from blueprint-core is unavailable in
// the browser, but toGraph never reaches that branch when given a compiled graph).
// Strip export keywords from EvalResult, Graph, toGraph.

let evalSrc = readFileSync(resolve(srcDir, 'evaluator.js'), 'utf8');

// Remove import lines
evalSrc = evalSrc.replace(/^import .+\n/gm, '');

// Strip export keywords from classes and functions
evalSrc = evalSrc.replace(/^export class EvalResult/m, 'class EvalResult');
evalSrc = evalSrc.replace(/^export class Graph/m, 'class Graph');
evalSrc = evalSrc.replace(/^export function toGraph/m, 'function toGraph');
evalSrc = evalSrc.replace(/^export function matchesType/m, 'function matchesType');

// ── Assemble IIFE ─────────────────────────────────────────────────────────────

const banner = `/**
 * @codeforamerica/blueprint-rules-engine — browser bundle
 * Exposes: window.RulesEngine = { toGraph }
 *
 * Generated by scripts/build-browser.js. Do not edit directly.
 */`;

const bundle = `${banner}
(function () {
'use strict';

${celSrc.trim()}

${evalSrc.trim()}

window.RulesEngine = { toGraph };
})();
`;

const outPath = resolve(distDir, 'browser.js');
writeFileSync(outPath, bundle);
console.log(`Wrote ${outPath}`);
