#!/usr/bin/env node
/**
 * Builds dist/browser.js — a self-contained IIFE bundle of evaluateGraph
 * for use in browser environments.
 *
 * Only evaluateGraph is included. The evaluate() function is excluded because
 * it depends on compileRuleset() from @codeforamerica/blueprint-core (a Node.js
 * build step). Browser callers receive pre-compiled *-graph.yaml documents from
 * the build pipeline and evaluate them directly.
 *
 * Exposed as: window.RulesEngine = { evaluateGraph }
 *
 * Usage: node scripts/build-browser.js
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const srcDir  = resolve(__dirname, '..', 'src');
const distDir = resolve(__dirname, '..', 'dist');

mkdirSync(distDir, { recursive: true });

// ── cel.js ────────────────────────────────────────────────────────────────────
// No imports. Strip the `export` keyword only.

const celSrc = readFileSync(resolve(srcDir, 'cel.js'), 'utf8')
  .replace(/^export /m, '');

// ── evaluator.js ──────────────────────────────────────────────────────────────
// Strip:
//   - import statements (lines beginning with `import`)
//   - buildDefaultScope (only used by evaluate(), not evaluateGraph())
//   - evaluate() itself (requires compileRuleset from blueprint-core)
// Keep: topoSort, resolveInputPath, evaluateGraph

let evalSrc = readFileSync(resolve(srcDir, 'evaluator.js'), 'utf8');

// Remove import lines
evalSrc = evalSrc.replace(/^import .+\n/gm, '');

// Remove the JSDoc + function body for buildDefaultScope.
// Bounded: from the section comment up to (not including) the Evaluator section.
evalSrc = evalSrc.replace(
  /\/\/ ── Default scope building ─+\n[\s\S]*?(?=\/\/ ── Evaluator)/,
  '',
);

// Remove the JSDoc + export function evaluate(...) up to (not including) evaluateGraph JSDoc.
// The evaluate() function is the first export; evaluateGraph follows it.
evalSrc = evalSrc.replace(
  /\/\*\*\n \* Evaluate a ruleset[\s\S]*?(?=\/\*\*\n \* Evaluate a compiled graph)/,
  '',
);

// Strip export keyword from evaluateGraph
evalSrc = evalSrc.replace(/^export function evaluateGraph/m, 'function evaluateGraph');

// ── Assemble IIFE ─────────────────────────────────────────────────────────────

const banner = `/**
 * @codeforamerica/blueprint-rules-engine — browser bundle
 * Exposes: window.RulesEngine = { evaluateGraph }
 *
 * Generated by scripts/build-browser.js. Do not edit directly.
 */`;

const bundle = `${banner}
(function () {
'use strict';

${celSrc.trim()}

${evalSrc.trim()}

window.RulesEngine = { evaluateGraph };
})();
`;

const outPath = resolve(distDir, 'browser.js');
writeFileSync(outPath, bundle);
console.log(`Wrote ${outPath}`);
