openapi: 3.1.0
x-domain: households
info:
  title: Household Service API
  version: 1.0.0
  description: |
    REST API for managing household records. The specification defines CRUD operations
    for creating, reading, updating, and deleting households.
  contact:
    name: API Support
    email: support@example.com
servers:
- url: https://api.example.com
  description: Production server
- url: http://localhost:8080
  description: Local development server
tags:
- name: Households
  description: Manage household records.
paths:
  "/households":
    get:
      summary: List households
      description: Retrieve a paginated list of households.
      operationId: listHouseholds
      tags:
      - Households
      parameters:
      - "$ref": "./components/common-parameters.yaml#/SearchQueryParam"
      - "$ref": "./components/common-parameters.yaml#/LimitParam"
      - "$ref": "./components/common-parameters.yaml#/OffsetParam"
      responses:
        '200':
          description: A paginated collection of households.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HouseholdList"
        '400':
          "$ref": "./components/common-responses.yaml#/BadRequest"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
    post:
      summary: Create a household
      description: Create a new household record.
      operationId: createHousehold
      tags:
      - Households
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/HouseholdCreate"
      responses:
        '201':
          description: Household created successfully.
          headers:
            Location:
              description: URL of the newly created household resource.
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Household"
        '400':
          "$ref": "./components/common-responses.yaml#/BadRequest"
        '422':
          "$ref": "./components/common-responses.yaml#/UnprocessableEntity"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
  "/households/{householdId}":
    parameters:
    - "$ref": "#/components/parameters/HouseholdIdParam"
    get:
      summary: Get a household
      description: Retrieve a single household by identifier.
      operationId: getHousehold
      tags:
      - Households
      responses:
        '200':
          description: Household retrieved successfully.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Household"
              examples:
                HouseholdExample1:
                  "$ref": "./examples/households.yaml#/HouseholdExample1"
        '404':
          "$ref": "./components/common-responses.yaml#/NotFound"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
    patch:
      summary: Update a household
      description: Apply partial updates to an existing household.
      operationId: updateHousehold
      tags:
      - Households
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/HouseholdUpdate"
      responses:
        '200':
          description: Household updated successfully.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Household"
        '400':
          "$ref": "./components/common-responses.yaml#/BadRequest"
        '404':
          "$ref": "./components/common-responses.yaml#/NotFound"
        '422':
          "$ref": "./components/common-responses.yaml#/UnprocessableEntity"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
    delete:
      summary: Delete a household
      description: Permanently remove a household record.
      operationId: deleteHousehold
      tags:
      - Households
      responses:
        '204':
          description: Household deleted successfully.
        '404':
          "$ref": "./components/common-responses.yaml#/NotFound"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
components:
  parameters:
    HouseholdIdParam:
      name: householdId
      in: path
      required: true
      description: Unique identifier of the household.
      schema:
        type: string
        format: uuid
      example: a1b2c3d4-e5f6-7890-abcd-ef1234567890
  schemas:
    Household:
      "$ref": "./components/household.yaml#/Household"
    HouseholdCreate:
      allOf:
      - "$ref": "./components/household.yaml#/Household"
      - type: object
        description: |
          Payload to create a new household record.
          
          Note: id, createdAt, and updatedAt are server-generated (readOnly) and will be returned in the response.
    HouseholdUpdate:
      allOf:
      - "$ref": "./components/household.yaml#/Household"
      - type: object
        description: |
          Payload to update household members. Partial updates are supported.
          
          Note: id, createdAt, and updatedAt are server-generated (readOnly) and cannot be updated.
        minProperties: 1
    HouseholdList:
      type: object
      additionalProperties: false
      required:
      - items
      - total
      - limit
      - offset
      properties:
        items:
          type: array
          items:
            "$ref": "#/components/schemas/Household"
        total:
          type: integer
          minimum: 0
          description: Total number of households available.
        limit:
          type: integer
          minimum: 1
          maximum: 100
          description: Maximum number of households requested.
        offset:
          type: integer
          minimum: 0
          description: Number of items skipped before the current page.
        hasNext:
          type: boolean
          description: Indicates whether more households are available beyond the current
            page.
