/**
 * @codeforamerica/blueprint-rules-engine — browser bundle
 * Exposes: window.RulesEngine = { evaluateGraph }
 *
 * Generated by scripts/build-browser.js. Do not edit directly.
 */
(function () {
'use strict';

/**
 * CEL expression evaluator.
 *
 * Taken directly from the spike's mock-server/src/cel-evaluator.js.
 * Transforms CEL syntax to JavaScript-compatible equivalents before
 * evaluating via Function constructor.
 *
 * Supported CEL constructs:
 *   has(field)              — field is present, non-null, non-empty string
 *   .size()                 — collection or string length
 *   .contains(value)        — collection or string membership
 *   "x" in arr              — array membership with string literal LHS
 *   $var in arr             — array membership with variable LHS
 *   .filter(var, pred)      — filter collection
 *   .map(var, expr)         — transform collection
 *   .all(var, pred)         — all items satisfy predicate
 *   .exists(var, pred)      — any item satisfies predicate
 */

/**
 * Evaluate a CEL expression against a context object.
 *
 * @param {string} expr    - CEL expression string
 * @param {Object} context - flat map of variable names to values
 * @returns {*} evaluated result; undefined on error
 */
function evaluateCEL(expr, context = {}) {
  if (!expr || typeof expr !== 'string') return undefined;
  try {
    const jsExpr = expr
      .replace(/\bhas\(([\w.]+)\)/g, '(typeof $1 !== "undefined" && $1 !== null && $1 !== "")')
      .replace(/\.size\(\)/g, '.length')
      .replace(/\.contains\(([^)]+)\)/g, '.includes($1)')
      .replace(/"([^"]+)"\s+in\s+([\w$.]+)/g, '(Array.isArray($2) ? $2.includes("$1") : false)')
      .replace(/([$][\w$.]+)\s+in\s+([$][\w$.]+)/g, '(Array.isArray($2) ? $2.includes($1) : false)')
      .replace(/\.(filter|map)\((\w+),\s*([^)]+(?:\([^)]*\))*[^)]*)\)/g, (_, fn, v, pred) => `.${fn}(${v} => (${pred}))`)
      .replace(/\.all\((\w+),\s*([^)]+(?:\([^)]*\))*[^)]*)\)/g, '.every($1 => ($2))')
      .replace(/\.exists\((\w+),\s*([^)]+(?:\([^)]*\)[^)]*)*)\)/g, '.some($1 => ($2))');

    // eslint-disable-next-line no-new-func
    const fn = new Function(...Object.keys(context), `return (${jsExpr});`);
    return fn(...Object.values(context));
  } catch (e) {
    return undefined;
  }
}

/**
 * Blueprint rules evaluator.
 *
 * Walks a compiled graph in topological order (Kahn's algorithm) and evaluates
 * each fact's CEL expression against a (possibly partial) set of inputs.
 *
 * Returns facts in three states, mirroring FactGraph's Complete/Placeholder/Incomplete:
 *   complete    — fact resolved; all inputs explicitly provided
 *   placeholder — fact resolved; at least one input used a schema default
 *   missing     — fact could not compute; missing required input paths (tracked)
 *   errors      — fact threw during evaluation
 *
 * Input scope: top-level named inputs (household, policy) are placed directly in
 * scope so expressions like "household.monthlyIncome < policy.limit" resolve via
 * JavaScript property access.
 *
 * @module evaluator
 */


// ── Topological sort (Kahn's algorithm) ──────────────────────────────────────

function topoSort(factNames, dependencies) {
  const factSet = new Set(factNames);
  const inDegree = Object.fromEntries(factNames.map(f => [f, 0]));
  const outEdges = Object.fromEntries(factNames.map(f => [f, []]));

  for (const [fact, deps] of Object.entries(dependencies)) {
    if (!factSet.has(fact)) continue;
    for (const dep of deps) {
      if (factSet.has(dep)) {
        inDegree[fact]++;
        outEdges[dep].push(fact);
      }
    }
  }

  const queue = factNames.filter(f => inDegree[f] === 0);
  const ordered = [];
  while (queue.length) {
    const n = queue.shift();
    ordered.push(n);
    for (const m of outEdges[n]) {
      inDegree[m]--;
      if (inDegree[m] === 0) queue.push(m);
    }
  }
  return ordered;
}

// ── Input path resolution ─────────────────────────────────────────────────────

/**
 * Resolve a JSONPath input key ($.household.monthlyExpenses, $.household.members[])
 * to its value from the caller's named input objects.
 */
function resolveInputPath(path, inputs) {
  const clean = path.slice(2).replace(/\[\]$/, '');
  const parts = clean.split('.');
  let node = inputs;
  for (const part of parts) {
    if (node == null || typeof node !== 'object') return undefined;
    node = node[part];
  }
  return node;
}

// ── Evaluator ─────────────────────────────────────────────────────────────────

/**
 * Evaluate a compiled graph directly against a (possibly partial) set of inputs.
 *
 * Accepts the output of compileRuleset() or a parsed *-graph.yaml document.
 * Unlike evaluate(), this function takes a pre-compiled graph and skips the
 * compilation step. No namespace-level schema defaults are applied — all
 * inputs must be explicit.
 *
 * @param {Object} graph   - compiled graph ({ facts, dependencies, outputs, inputs, ... })
 * @param {Object} inputs  - named input objects, e.g. { household: { ... } }
 * @returns {{ complete: Object, placeholder: Object, missing: Object, errors: Object }}
 */
function evaluateGraph(graph, inputs) {
  const factNames = Object.keys(graph.facts);
  const ordered = topoSort(factNames, graph.dependencies);

  const scope = { ...inputs };

  const complete = {};
  const placeholder = {};
  const missing = {};
  const errors = {};
  const resolved = {};

  for (const factName of ordered) {
    const deps = graph.dependencies[factName] ?? [];
    const missingPaths = new Set();

    for (const dep of deps) {
      if (dep.startsWith('$.')) {
        const val = resolveInputPath(dep, inputs);
        if (val === undefined) {
          missingPaths.add(dep);
        }
      } else {
        if (resolved[dep] === undefined && !errors[dep]) {
          if (missing[dep]) {
            for (const p of missing[dep]) missingPaths.add(p);
          } else {
            missingPaths.add(dep);
          }
        }
      }
    }

    if (missingPaths.size > 0) {
      missing[factName] = [...missingPaths];
      continue;
    }

    const factDecl = graph.facts[factName];
    const expr = factDecl?.expression;
    if (!expr) continue;

    const result = evaluateCEL(expr, scope);
    if (result === undefined) {
      errors[factName] = `Expression failed to evaluate: ${expr}`;
    } else {
      resolved[factName] = result;
      scope[factName] = result;
      complete[factName] = result;
    }
  }

  const outputSet = new Set(graph.outputs);
  return {
    complete:    Object.fromEntries(Object.entries(complete).filter(([k]) => outputSet.has(k))),
    placeholder: Object.fromEntries(Object.entries(placeholder).filter(([k]) => outputSet.has(k))),
    missing:     Object.fromEntries(Object.entries(missing).filter(([k]) => outputSet.has(k))),
    errors:      Object.fromEntries(Object.entries(errors).filter(([k]) => outputSet.has(k))),
  };
}

window.RulesEngine = { evaluateGraph };
})();
