name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  validate-and-test:
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'changeset-release/')"
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20'

      - run: npm install

      - name: Run preflight checks
        run: npm run preflight
